WITH RQ1 AS 
	(SELECT INTERVENANT.ID AS INTERV_ID, VILLE, PROVINCE, PAYS, NUM_TEL FROM 
			INTERVENANT JOIN ADRESSE ON (ADRESSE.ID = INTERVENANT.ADRESSE_ID )), 
	RQ2 AS
		(SELECT ANNONCE.ID AS ANNONCE_ID, VENDEUR_ID, PRODUIT.ID, NOM, 
			PRODUIT.DESCRIPTION AS DESCRIP, PRIX, TAILLE, LONGUEUR, LARGEUR, PROFONDEUR, CATEGORIE, ETAT,
			DATE_PUB, TITRE, FINALISEE FROM ANNONCE JOIN PRODUIT ON (PROD_ID = PRODUIT.ID)) 
	SELECT ANNONCE_ID, NOM, DESCRIP, PRIX, TAILLE, LONGUEUR, LARGEUR, PROFONDEUR, CATEGORIE, ETAT,  
				DATE_PUB, TITRE, VILLE, PROVINCE, PAYS, NUM_TEL, FINALISEE FROM RQ1 JOIN RQ2 ON (VENDEUR_ID = INTERV_ID); 